### ISSUE TITLE
Version of the new EPUB Revision

### ISSUE THREAD

**Issue by wareid** [w3c/epub-wg#8] opened 2020-09-09 17:55 UTC
The current version of EPUB is 3.2. 

For this upcoming work, we will need a new version number, we've been calling the work EPUB 3.x so far.

**Comment by dauwhe** [comment] 2020-09-09 17:56
I suggest EPUB 3.3.

**Comment by dauwhe** [comment] 2020-09-09 17:57
Note: The `version` attribute of the `package` element will remain `3.0`, as has been true in EPUB 3.0, EPUB 3.0.1, EPUB 3.1, and EPUB 3.2.

**Comment by toshiakikoike** [comment] 2020-09-10 09:56
> Note: The `version` attribute of the `package` element will remain `3.0`, as has been true in EPUB 3.0, EPUB 3.0.1, EPUB 3.1, and EPUB 3.2.

very important
+1

**Comment by iherman** [comment] 2020-09-10 10:13
Just to make the choices more explicit: I guess our choices are EPUB 3.3 or EPUB 3.2.1.

**Comment by iherman** [comment] 2020-09-10 10:14
(We have to be careful about the [bike shedding effect](https://en.wikipedia.org/wiki/Law_of_triviality), though :-)

**Comment by shiestyle** [comment] 2020-09-10 11:50
+1 for EPUB 3.3.

Because it's easy to understand the first version of W3C standard.

**Comment by iherman** [comment] 2020-09-10 11:57
> +1 for EPUB 3.3.
> 
> Because it's easy to understand the first version of W3C standard.

This is actually a very good point. It makes me vote for 3.3 as well.

**Comment by deborahgu** [comment] 2020-09-11 14:51
3.3 is perfect and uncomplicated.

**Comment by dauwhe** [comment] 2020-09-11 15:21
In [today's meeting](https://www.w3.org/2020/09/11-epub-minutes.html) we resolved to use 3.3. We will confirm on the next WG call.

**Comment by dshioham** [comment] 2020-09-11 16:12
+1 on 3.3

**Comment by HadrienGardeur** [comment] 2020-09-14 10:21
> Note: The `version` attribute of the `package` element will remain `3.0`, as has been true in EPUB 3.0, EPUB 3.0.1, EPUB 3.1, and EPUB 3.2.

Is there any plan to convey that information differently though?

Differences between 3.0, 3.0.1 and 3.2 are minor, 3.1 is barely used but if we're heading towards HTML serialization in 3.3 it seems important to indicate that a publication is an EPUB 3.3 without requiring a "sniff test" (inspecting the OPF to detect `text/html`).

**Comment by wareid** [comment] 2020-09-14 18:52
> > Note: The `version` attribute of the `package` element will remain `3.0`, as has been true in EPUB 3.0, EPUB 3.0.1, EPUB 3.1, and EPUB 3.2.
> 
> Is there any plan to convey that information differently though?
> 
> Differences between 3.0, 3.0.1 and 3.2 are minor, 3.1 is barely used but if we're heading towards HTML serialization in 3.3 it seems important to indicate that a publication is an EPUB 3.3 without requiring a "sniff test" (inspecting the OPF to detect `text/html`).

It might not have been obvious in the minutes (I'll check and amend if needed), but HTML serialization was brought up and the consensus was that we will start with 3.3 for now, but it is possible something like serialization might bump the version up higher (3.4, 3.5 etc). It is a good point that we may need a "hint" to reading systems that this book has HTML, I'm sure it'll come up when we reach that topic. 3.3 can be considered our starting point.

**Comment by iherman** [comment] 2020-09-15 07:14
I think having a hint on the subversion will become necessary at some point indeed. Because there was a very strong push back on changing the `version` attribute to avoid backward incompatibility problems we should not touch that. Maybe we will need some `version-minor=3.3` (we can bikeshed on the attribute name).

**Comment by mattgarrish** [comment] 2020-09-15 10:25
> Maybe we will need some `version-minor=3.3` (we can bikeshed on the attribute name).

Right, I know we discussed various approaches for 3.1 to avoid a version bump but still signal a change, one I seem to recall being to use something like an `edition` attribute.

The problem is that it still doesn't tell you anything specific about the content until you go sniffing, but those are discussions for another day.

**Comment by iherman** [comment] 2020-10-24 13:54
Resolved on the [WG call of 2020-09-11](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-09-11-epub):

> [Resolution #1: The version of this revision of EPUB will be 3.3](https://www.w3.org/publishing/groups/epub-wg/Meetings/Minutes/2020-09-11-epub#resolution1)

**Comment by iherman** [comment] 2020-10-24 13:55
@wareid @shiestyle Propose closing...

**Closed** 2020-11-26 16:48 UTC
Labels: Propose closing
